menu title Avaota A1 mainline boot
timeout 20
default mainline

label mainline
  menu label Linux 7.2 / Buildroot 2026.05.1
  linux /Image
  fdt /sun55i-t527-avaota-a1.dtb
  append console=ttyS0,115200 earlycon root=/dev/mmcblk1p2 rootwait rw fsck.repair=yes net.ifnames=0
